package tds.exam;

/**
 * Parameters for expandable exam optional properties
 */
public enum ExpandableExamParameters {
    EXPANDABLE_PARAMS_EXAM_ACCOMMODATIONS,
    EXPANDABLE_PARAMS_ITEM_RESPONSE_COUNT,
    EXPANDABLE_PARAMS_UNFULFILLED_REQUEST_COUNT,
    EXPANDABLE_PARAMS_EXAM_SEGMENTS,
    EXPANDABLE_PARAMS_EXAM_PAGE_AND_ITEMS,
    EXPANDABLE_PARAMS_EXAM_PAGE_ITEMS_AND_RESPONSES,
    EXPANDABLE_PARAMS_EXAM_NOTES,
    EXPANDABLE_PARAMS_EXAMINEE_ATTRIBUTES_AND_RELATIONSHIPS,
    EXPANDABLE_PARAMS_EXAM_STATUS_DATES
}
